<a href="https://colab.research.google.com/github/egipot/freeCodeCamp_tensorFlow/blob/main/freeCodeCamp_TensorFlow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/introduction-to-tensorflow
#Reference: #https://www.tensorflow.org/guide/tensor

#READ also later: https://www.freecodecamp.org/news/tensorflow-basics/

import tensorflow as tf

#create different tensors
text = tf.Variable('string', tf.string)  #scalar == one dimension or one value only
number = tf.Variable(324, tf.int64)
floating = tf.Variable (3.567, tf.float64)

#rank or degree of tensors
rank1_tensor = tf.Variable(['Test1', 'Test2'], tf.string) #array - rank1 = more than one item or dimension
rank2_tensor = tf.Variable([['Test1', 'Test2'], ['Passed', 'In-Progress']], tf.string) # rank2 = list in a list == matrix
# To determine the rank of a tensor is the deepest level of a nested list



In [ ]:
#determine the rank of a tensor:
tf.rank(text)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(floating)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
#determine the rank of a tensor:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
#determine the rank of a tensor:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
#determine the shape of tensors
text.shape

TensorShape([])

In [ ]:
number.shape

TensorShape([])

In [ ]:
floating.shape

TensorShape([])

In [ ]:
rank1_tensor.shape

TensorShape([2])

In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

In [ ]:
rank3_tensor = tf.Variable([['Test1', 'Test2', 'Test3'], ['Passed', 'In-Progress', 'Pending'], ['Engr1', 'Engr2', 'Engr3']], tf.string)
rank3_tensor.shape

TensorShape([3, 3])

In [ ]:
#1.How to change the shape of a tensor
#1a.First, create
tensor1 = tf.ones([1,2,3])
print(tensor1)
print(f"\ntensor1's shape:  {tensor1.shape}")

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

tensor1's shape:  (1, 2, 3)


In [ ]:
#1b. Second, reshape
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [ ]:
#1c.-1 tells the tensor to calculate the size of the dimension in that place

tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

#NOTE: the number of elements in the reshaped tensor MUST match the number in the original

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**Type of Tensors:**

*   Variable - the only NOT immutable i.e. the value may change during execution; hence, variable is used when we want to potentially change the value of our tensor
*   Constant
*   Placeholder
*   SparseTensor







In [ ]:
#https://www.tensorflow.org/guide/tensor
#Evaluating tensor - for use later
#with tf.Session() as sess:
#  tensor.eval()


In [ ]:
%tensorflow_version 2.x

import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
t = tf.zeros([5,5,5,5])
t

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

  

In [ ]:
t = tf.reshape(t, [625])
t

<tf.Tensor: shape=(625,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
t = tf.reshape(t, [125, -1]) #-1 means that tensorFlow will decide/infer what the shape needs to be
t

<tf.Tensor: shape=(125, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0.